<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2cfa3c50-fe6a-4ef1-b19d-3523861ee143</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_172_category_uncategorized</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/article[2]/footer[1]/div[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#post-5514 [rel]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>