<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0e07aa10-3cd6-4581-8d5c-239e5d8876ce</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_172_trien_khai_du_an_dai_hoc_khong_rac_t</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/article[3]/header[1]/h2[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#post-1718 .entry-title a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>