<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d18508ec-9540-4b00-a0ab-35e321cd5367</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_172_category_social</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/article[1]/footer[1]/div[2]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[rel='category\ tag']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>